import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Providers from "@/utils/Providers";
import Navbar from "@/components/Navbar";
import Provider from "@/util/Provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Providers>
          <Navbar/>
          <Provider>
            {children}
          </Provider>
        </Providers>
      </body>
    </html>
  );
}
